### ISSUE TITLE
Accept individual path to `paths` instead of an array?

### ISSUE THREAD

**Issue by bebraw** [webpack-contrib/purifycss-webpack-plugin#52]
It might be useful if `paths` allowed you to pass a single path too. Now it fails rather messily if you try this. If you decide against this, a nicer warning wouldn't hurt.

I can PR this if you want.

**Comment by andersontr15** [comment]
Paths currently as an array doesn't work for me. Is it not compatible trying to glob multiple directories?

**Comment by bebraw** [comment]
@andersontr15 The implementation has changed a lot. The plugin doesn't come with glob anymore and it actually expects absolute paths instead. I would need some example to say anything more. Please see the verbose mode as well.
