### ISSUE TITLE
CSS + SCSS configuration

### ISSUE THREAD

**Issue by dhoomm** [webpack-contrib/purifycss-webpack-plugin#54]
I load both .css and .scss as

`
{
                    test: /\.scss$/,
                    loader: ExtractTextPlugin.extract("style-loader", "css-loader!sass-loader"),
                    include: paths,
                },
`
`
                {
                    test: /\.css$/,
                    loader: ExtractTextPlugin.extract("style-loader", "css-loader"),
                    include: paths
                },
            ]
`

Now when i apply PurifyCss plugin, it does not include any style from any of .scss files. (works as expected for .css files). When i remove purify plugin, styles from .scss files are loaded.

**Comment by Kikobeats** [comment]
check #55

**Comment by dmackerman** [comment]
You'll need to configure the `resolveExtensions` config.

```
    new PurifyCSSPlugin({
      basePath: path.join(__dirname, 'portal', 'js'),
      resolveExtensions: ['.html', '.js'],
      paths: [
        'app/**/*.js',
        'tpl/**/*.html',
      ],
    }),
```

**Comment by bebraw** [comment]
Closing in favor of #55.
