### ISSUE TITLE
Webpack2 support

### ISSUE THREAD

**Issue by mnasyrov** [webpack-contrib/purifycss-webpack-plugin#60]
First of all, thank for the plugin!

Does it support webpack2 officially?
I got 'unmet peer dependency' npm warning when install the plugin together with webpack2.
```
└── UNMET PEER DEPENDENCY webpack@2.1.0-beta.27

npm WARN purifycss-webpack-plugin@2.0.3 requires a peer of webpack@^1.9.11 but none was installed.
```

**Comment by jachaf6746** [comment]
+1

**Comment by muminoff** [comment]
+1

**Comment by Tibfib** [comment]
This seems to work just fine in webpack2... Any word on official support?

**Comment by bebraw** [comment]
This definitely works with webpack 2. I have a little demo at the repository now.
