### ISSUE TITLE
React / Webpack app

### ISSUE THREAD

**Issue by dmt0** [webpack-contrib/purifycss-webpack-plugin#61]
Hi!
Trying to config this in my project, and so far no effect on css, and no output during build. Here's my webpack config:

    new ExtractTextPlugin('bundle.css'),
    new purifycss({
      basePath: path.join(__dirname, '../src'),
      resolveExtensions: ['.html', '.js'],
      paths: [
        '../src/**/*.js',
        'index.html',
      ],
      purifyOptions: {
        minify: true,
        info: true,
        rejected: true,
     }

Tried with just __dirname as basePath, tried without paths, still no output and my bundle.css stays the same. What am I doing wrong?

**Comment by bebraw** [comment]
I think you need to set `resolveExtensions: ['.html']`. Otherwise it will go through `node_modules/react` and pick up all sorts of classes from there. That effectively breaks purifying.

**Comment by dmt0** [comment]
Tried that, same result.

**Comment by bebraw** [comment]
I would need a standalone example to say anything concrete. If you can set up a repo, that would be great.
